import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const BUILD_DIR = resolve("../../build/emscripten-release/core");
const TARGET_DIR = resolve("src/ts/wasm");

const GENERATED_HEADER = [
	'/* eslint-disable */',
	'// Generated by Emscripten. Do not edit by hand.',
	'// Regenerate with: npm run build:wasm',
	'',
].join('\n');

async function main(){
	await mkdir(TARGET_DIR, { recursive: true });
	await copyFile(
		resolve(BUILD_DIR, "tachyon.wasm"),
		resolve(TARGET_DIR, "tachyon.wasm")
	);

	const jsBody = await readFile(resolve(BUILD_DIR, 'tachyon.js'), 'utf8');
	await writeFile(
		resolve(TARGET_DIR, "tachyon.js"),
		`${GENERATED_HEADER}\n${jsBody}`
	);

	console.log("WASM artefacts copied");
}

main().catch((err) => {
	console.error("Failed to process WASM artefacts: ", err);
	process.exit(1);
})